
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mutkltxqouslkneswzyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11dGtsdHhxb3VzbGtuZXN3enl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNDg3MDksImV4cCI6MjA2MTgyNDcwOX0.HJelC_PkL_M5A6B_nMr9geJ5ImfiLegDBQgSFFxu6y4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
